### ISSUE TITLE
puppetize ldap2s3

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/auth0-scripts#16]
contact me for setup help

**Comment by jdow** [comment]
I have this in puppet, but it's not working yet. It looks like we don't have python3 installed on the hosts, so that'll need to happen first, and potentially need to package the dependencies if there aren't existing RPMs.

**Comment by gdestuynder** [comment]
@jdow that does not need any kind of reinstall of the OS right?
(otherwise id port it to python2, but since most IAM things now already standardized on p3 id rather just keep things that way if possible)

For example on CentOS7 this means having something like IUS installed (https://centos7.iuscommunity.org/ius-release.rpm)

**Comment by jdow** [comment]
I was able to install the packages: python2-boto3, python2-ldap3 and PyYAML, and now the script executes without error.

**Comment by gdestuynder** [comment]
@jdow i think this is fixed, though, there's an update to deploy as well cc @andrewkrug :+1: https://github.com/mozilla-iam/auth0-scripts/pull/24

Currently there is a single snapshot of this in dev, but its not up to date because the new script is not running yet

**Comment by gdestuynder** [comment]
hes done it
